### ISSUE TITLE
想问一下定时发送该怎么写？

### ISSUE THREAD

**Issue by aion1998** [Jie2GG/Native.Framework#140]
到现在还是搞不懂咋写，还是这不能整定时？

**Comment by littlegao233** [comment]
1. - 先找个获取到的CQEvent存变量
2. - using System.Timers;
3. - > ` public Timer Cycle = new Timer() { AutoReset = true, Interval = 时间间隔毫秒};` 
//创建timer
4. - > ` public void Cycle_Elapsed(object sender, ElapsedEventArgs e)`
       ` {`
         `  这里写定时的代码(用之前存的CQEvent.cqApi调用功能)`
     `  }`
5. - > `Cycle.Elapsed += TimeCycle.Cycle_Elapsed;`
//增加计时器Elapsed事件
6. - > 自由花灰贰叁叁


`

**Comment by Jie2GG** [comment]
正解, 使用系统定时器即可完成定时任务.

**Comment by aion1998** [comment]
> 1. * 先找个获取到的CQEvent存变量
> 2. * using System.Timers;
> 3. * > ` public Timer Cycle = new Timer() { AutoReset = true, Interval = 时间间隔毫秒};`
>      > //创建timer
> 4. * > ` public void Cycle_Elapsed(object sender, ElapsedEventArgs e)`
>      > ` {`
>      > `  这里写定时的代码(用之前存的CQEvent.cqApi调用功能)`
>      > `  }`
> 5. * > `Cycle.Elapsed += TimeCycle.Cycle_Elapsed;`
>      > //增加计时器Elapsed事件
> 6. * > 自由花灰贰叁叁
> 
> `

感谢
