### ISSUE TITLE
..咋感觉我新拉的代码和原来的项目不一样

### ISSUE THREAD

**Issue by aion1998** [Jie2GG/Native.Framework#146]
..是不是整体更新换过。
..还有那个定时的我还是写不出来，有人能给个简单的demo示范一下吗！
或者发个博客园也行

**Comment by Jie2GG** [comment]
最新版本的 Sdk 已经进入长期维护, 只需要按照 WIKI 走一遍流程即可, 还有不理解的地方也欢迎进入QQ群了解 711841640

**Comment by cqbef** [comment]
关於范例，你可以查看 <kbd>[Example](https://github.com/Jie2GG/Native.Framework/tree/Example)</kbd>分支，该分支版本目前是对应4.1版本而建立。
